name: Build Krypton Client

on:
  workflow_dispatch:  # Allows you to manually trigger this from the Actions tab

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set up GH_TOKEN for Electron Builder
        run: echo "//github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc

      - name: Build app with electron-builder
        run: npm run dist

      - name: Upload dist files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: krypton-build-${{ matrix.os }}
          path: dist/
