name: Build and Release Krypton Client

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set up GH_TOKEN for Electron Builder
        run: echo "//github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc

      - name: Build app
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # This sets the environment variable for Electron Builder

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: krypton-build-${{ matrix.os }}
          path: dist/

      - name: Create a GitHub release
        id: release
        run: |
          TAG_NAME="v1.0.0"
          RELEASE_NAME="Release $TAG_NAME"
          BODY="Krypton Client release version $TAG_NAME."
          gh release create $TAG_NAME dist/* --title "$RELEASE_NAME" --notes "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

